"""Professions, AI tools, use cases and attitudes used by the persona generator.

Weighted lists are written as compact strings: "Name:weight; Other name:weight".
"""

from __future__ import annotations


def w(spec: str) -> dict[str, float]:
    """Parse "A:3; B:1.5" into {"A": 3.0, "B": 1.5}."""
    out: dict[str, float] = {}
    for part in spec.split(";"):
        part = part.strip()
        if not part:
            continue
        name, _, weight = part.rpartition(":")
        out[name.strip()] = float(weight)
    return out


EDUCATION_LABELS = {
    "secondary": "Secondary school",
    "vocational": "Vocational training / apprenticeship",
    "bachelor": "Bachelor's degree",
    "master": "Master's degree",
    "phd": "PhD / doctorate",
    "none": "No degree (self-taught)",
    "medicine": "Medical degree",
}
# Typical age at which that education is finished.
EDUCATION_END_AGE = {
    "secondary": (18, 20), "vocational": (19, 21), "none": (18, 21), "bachelor": (21, 24),
    "master": (23, 26), "phd": (27, 31), "medicine": (24, 26),
}

SIZE_RANGES = {
    "1 (just me)": (1, 1),
    "2–10": (2, 10),
    "11–50": (11, 50),
    "51–250": (51, 250),
    "251–1,000": (251, 1000),
    "1,001–5,000": (1001, 5000),
    "5,000+": (5001, 60000),
}

SIZE_PRESETS = {
    "tech": w("2–10:1; 11–50:2; 51–250:3; 251–1,000:2; 1,001–5,000:1.5; 5,000+:2"),
    "corp": w("11–50:1; 51–250:2; 251–1,000:2; 1,001–5,000:2; 5,000+:3"),
    "smb": w("2–10:3; 11–50:3; 51–250:2; 251–1,000:1"),
    "public": w("51–250:1; 251–1,000:2; 1,001–5,000:3; 5,000+:3"),
    "school": w("11–50:2; 51–250:5; 251–1,000:1"),
    "hospital": w("51–250:1; 251–1,000:2; 1,001–5,000:3; 5,000+:2"),
    "practice": w("2–10:5; 11–50:2"),
    "agency": w("2–10:3; 11–50:4; 51–250:2; 251–1,000:0.5"),
    "university": w("251–1,000:1; 1,001–5,000:3; 5,000+:3"),
    "mixed": w("2–10:2; 11–50:2; 51–250:2; 251–1,000:2; 1,001–5,000:1; 5,000+:1"),
}

# Phrases used in bios for industries that are really institutions.
ORG_PHRASES = {
    "Public secondary school": "a public secondary school",
    "Private school": "a private school",
    "Primary school": "a primary school",
    "Vocational school": "a vocational school",
    "Language school": "a language school",
    "University": "a university",
    "Research institute": "a research institute",
    "Public hospital": "a public hospital",
    "Private clinic": "a private clinic",
    "Private practice": "a private practice",
    "Law firm": "a law firm",
    "National ministry": "a national ministry",
    "City administration": "the city administration",
    "EU institution": "an EU institution",
    "Regional government": "the regional government",
    "Public agency": "a public agency",
    "Pharmacy": "a pharmacy",
    "Newspaper": "a newspaper",
    "Public broadcaster": "the public broadcaster",
    "News agency": "a news agency",
}

CONCERNS = {
    "accuracy": "inaccurate or made-up answers (hallucinations)",
    "privacy": "data privacy, GDPR and confidential information",
    "deskilling": "losing my own skills by relying on it too much",
    "job": "job security in my field",
    "copyright": "copyright and who owns AI-generated work",
    "bias": "bias and discrimination in the outputs",
    "env": "energy use and environmental impact",
    "cost": "subscription and licence costs",
    "policy": "unclear rules from my employer",
    "ai_act": "compliance with the EU AI Act",
    "bland": "generic, bland output that obviously sounds like AI",
    "cheating": "students using AI instead of actually learning",
    "security": "security of AI-generated code and configurations",
    "dependence": "dependence on a few big US tech companies",
    "liability": "unclear liability when AI contributes to a mistake",
    "pay": "clients using AI as an argument to pay less",
    "human": "AI replacing human contact where it matters",
    "misinfo": "misinformation and deepfakes",
}

PET_PEEVES = [
    "the overly polite, wordy tone of AI answers",
    "when it confidently invents sources or numbers",
    "having to double-check everything it says",
    "colleagues pasting unedited AI text into emails",
    "the company blocking the tools that actually work",
    "subscriptions getting more expensive every year",
    "it losing the thread in long conversations",
    "AI-generated slides that everyone recognises instantly",
    "the endless AI hype on LinkedIn",
    "a new tool or feature every week that you're supposed to learn",
    "it refusing perfectly normal requests",
    "hitting usage limits exactly when a deadline is close",
    "managers who think AI makes every task take five minutes",
    "vendors adding an 'AI' label to features that aren't new",
    "meeting summaries that miss the one thing that mattered",
    "bullet points everywhere, even when you asked for prose",
]
# Only for people whose native language is not English.
PET_PEEVE_NON_ENGLISH = "noticeably weaker answers in {language} than in English"

HOBBIES = [
    "running", "cycling", "hiking", "photography", "board games", "cooking", "football",
    "reading sci-fi", "gardening", "bouldering", "yoga", "playing guitar", "video games",
    "travelling", "baking bread", "chess", "tennis", "volunteering at a food bank", "podcasts",
    "renovating an old flat", "fishing", "learning Spanish", "swimming", "amateur theatre",
    "coaching a kids' football team", "birdwatching", "3D printing", "knitting", "salsa dancing",
    "marathon training", "vinyl collecting", "camping", "crime novels", "drawing", "table tennis",
    "wild swimming", "home brewing", "sewing", "sourdough", "jazz", "fantasy football",
]

TITLE_LEVELS = ["junior", "mid", "senior", "lead", "head"]

# --------------------------------------------------------------------------- #
# Professions
# --------------------------------------------------------------------------- #
PROFESSIONS: list[dict] = [
    dict(
        key="software_engineer", label="Software developer", weight=10, female=0.22, min_age=21,
        titles=dict(
            junior=["Junior Software Engineer", "Junior Frontend Developer", "Junior Backend Developer"],
            mid=["Software Engineer", "Backend Developer", "Frontend Developer", "Full-Stack Developer",
                 "iOS Developer", "Android Developer"],
            senior=["Senior Software Engineer", "Senior Backend Engineer", "Senior Full-Stack Developer"],
            lead=["Tech Lead", "Staff Engineer", "Lead Developer"],
            head=["Engineering Manager", "Head of Engineering"]),
        freelance_title="Freelance Software Developer",
        industries=w("Software / SaaS:5; FinTech & banking:3; E-commerce & retail:2; IT services & consulting:3; "
                     "Automotive:1; Telecommunications:1; Gaming:0.7; HealthTech:1; Public sector IT:0.7; Logistics:0.7"),
        education=w("bachelor:4; master:5; none:1; vocational:1"),
        fields=["Computer Science", "Software Engineering", "Mathematics", "Physics", "Electrical Engineering",
                "Information Systems"],
        sizes="tech", work=w("remote:3; hybrid:6; office:1"), employment=w("employee:8; freelancer:2; founder:0.4"),
        salary=1.4, globalized=0.5, intensity=0.95,
        tools=w("ChatGPT:7; GitHub Copilot:8; Claude:6; Cursor:5; Claude Code:4; Gemini:2; Perplexity:1.5; "
                "JetBrains AI Assistant:2; OpenAI Codex:2; Windsurf:1; DeepSeek:0.7; "
                "local open-source models (Ollama):1"),
        uses=["generating boilerplate code", "debugging and explaining error messages", "writing unit tests",
              "refactoring legacy code", "writing technical documentation", "reviewing pull requests",
              "learning a new framework or language", "writing SQL queries and regexes",
              "prototyping features quickly", "upgrading dependencies and migrating code"],
        attitudes=w("enthusiast:3; pragmatist:5; cautious:1.5; skeptic:1"),
        concerns=w("accuracy:3; security:3; deskilling:3; privacy:2; job:1.5; cost:1; dependence:1"),
        wins=["an AI assistant wrote most of a test suite for a legacy module in one afternoon",
              "migrated a service to a new framework version in two days instead of two weeks with an AI agent",
              "the AI spotted a race condition I had been chasing for a whole day",
              "built a working internal tool over a weekend that nobody had time for"],
        fails=["the assistant invented a library function that doesn't exist and I lost an hour",
               "AI-generated code passed review but broke in production on an edge case",
               "an agent 'fixed' a failing test by deleting the assertion",
               "it kept suggesting a deprecated API even after I told it not to"]),
    dict(
        key="data_analyst", label="Data analyst / data scientist", weight=6, female=0.4, min_age=22,
        titles=dict(junior=["Junior Data Analyst"], mid=["Data Analyst", "BI Analyst", "Data Scientist"],
                    senior=["Senior Data Scientist", "Senior Data Analyst"], lead=["Lead Data Scientist", "Analytics Lead"],
                    head=["Head of Data", "Head of Analytics"]),
        freelance_title="Freelance Data Analyst",
        industries=w("E-commerce & retail:2; FinTech & banking:2; Insurance:1; Software / SaaS:2; Telecommunications:1; "
                     "Energy:1; Consumer goods:1; Healthcare:1; Market research:1; Public sector:0.7"),
        education=w("bachelor:3; master:6; phd:1.5"),
        fields=["Statistics", "Economics", "Mathematics", "Computer Science", "Physics", "Business Analytics",
                "Psychology"],
        sizes="corp", work=w("remote:2; hybrid:7; office:1"), employment=w("employee:9; freelancer:1"),
        salary=1.3, globalized=0.4, intensity=0.9,
        tools=w("ChatGPT:8; Claude:5; GitHub Copilot:4; Microsoft Copilot:3; Gemini:3; Julius AI:1; Cursor:2; Perplexity:1"),
        uses=["writing and optimising SQL queries", "cleaning messy data in Python", "explaining statistical methods",
              "building dashboards faster", "drafting insight summaries for stakeholders",
              "writing Excel and DAX formulas", "exploratory data analysis", "documenting data pipelines"],
        attitudes=w("enthusiast:3; pragmatist:5; cautious:2; skeptic:0.7"),
        concerns=w("accuracy:4; privacy:3; deskilling:2; job:1.5; bias:1"),
        wins=["turned a two-day ad-hoc analysis into a two-hour job",
              "the AI explained a mixed-effects model better than my old textbook",
              "it wrote a nasty SQL query with window functions correctly on the first try"],
        fails=["it produced a nice chart from a wrong join and nobody noticed for a week",
               "it confidently misinterpreted a p-value in a summary for management",
               "the numbers in its summary didn't match the actual table"]),
    dict(
        key="ml_engineer", label="Machine learning / AI engineer", weight=2, female=0.2, min_age=23, max_years=12,
        titles=dict(mid=["Machine Learning Engineer", "AI Engineer"], senior=["Senior ML Engineer", "Senior AI Engineer"],
                    lead=["Lead AI Engineer", "Staff ML Engineer"], head=["Head of AI"]),
        freelance_title="Freelance AI Engineer",
        industries=w("Software / SaaS:4; AI startup:3; FinTech & banking:1; Automotive:1; HealthTech:1; IT services & consulting:1"),
        education=w("master:6; phd:3; bachelor:2"),
        fields=["Computer Science", "Machine Learning", "Mathematics", "Physics", "Computational Linguistics"],
        sizes="tech", work=w("remote:3; hybrid:6; office:1"), employment=w("employee:8; freelancer:1; founder:1"),
        salary=1.6, globalized=0.6, intensity=1.0,
        tools=w("Claude:6; ChatGPT:6; GitHub Copilot:4; Cursor:5; Claude Code:4; "
                "open-source models (Llama, Mistral, Qwen):4; Gemini:2; Hugging Face:2"),
        uses=["prototyping LLM features", "evaluating model outputs", "writing training and data-processing code",
              "reading and summarising research papers", "building retrieval (RAG) pipelines",
              "generating synthetic test data"],
        attitudes=w("enthusiast:5; pragmatist:4; cautious:1; skeptic:0.3"),
        concerns=w("accuracy:3; ai_act:2; bias:2; cost:2; dependence:2; env:1"),
        wins=["shipped a ticket classifier in a week using an LLM instead of training a model",
              "an LLM-as-judge setup saved us hours of manual evaluation every sprint"],
        fails=["our RAG demo made up a refund policy in front of a client",
               "evaluation scores changed silently after a model update and nobody noticed"]),
    dict(
        key="devops", label="DevOps / cloud engineer", weight=2, female=0.12, min_age=22, max_years=16,
        titles=dict(junior=["Junior DevOps Engineer"], mid=["DevOps Engineer", "Cloud Engineer", "Site Reliability Engineer"],
                    senior=["Senior DevOps Engineer", "Senior Platform Engineer"], lead=["Lead SRE"],
                    head=["Head of Infrastructure"]),
        freelance_title="Freelance Cloud Engineer",
        industries=w("Software / SaaS:3; FinTech & banking:2; E-commerce & retail:1; IT services & consulting:2; Telecommunications:1"),
        education=w("bachelor:5; master:3; vocational:2; none:1"),
        fields=["Computer Science", "Information Systems", "Electrical Engineering", "Network Engineering"],
        sizes="tech", work=w("remote:3; hybrid:6; office:1"), employment=w("employee:8; freelancer:2"),
        salary=1.4, globalized=0.5, intensity=0.9,
        tools=w("ChatGPT:7; GitHub Copilot:6; Claude:5; Cursor:2; Gemini:2; Amazon Q Developer:1.5; Microsoft Copilot:1"),
        uses=["writing Terraform and Kubernetes manifests", "reading logs and stack traces", "writing Bash and Python scripts",
              "drafting incident post-mortems", "writing CI/CD pipelines", "explaining cloud bills"],
        attitudes=w("enthusiast:2; pragmatist:6; cautious:2; skeptic:1"),
        concerns=w("security:4; accuracy:3; privacy:2; deskilling:1"),
        wins=["found the root cause of an outage by pasting the logs in at 3 a.m.",
              "converted a pile of old shell scripts into clean Terraform in a few days"],
        fails=["it suggested a command that would have wiped a whole namespace",
               "it generated an IAM policy that was far too permissive"]),
    dict(
        key="qa", label="QA / test engineer", weight=1.5, female=0.4, min_age=21,
        titles=dict(junior=["Junior QA Engineer"], mid=["QA Engineer", "Test Automation Engineer"],
                    senior=["Senior QA Engineer"], lead=["QA Lead"], head=["Head of QA"]),
        freelance_title="Freelance QA Engineer",
        industries=w("Software / SaaS:4; FinTech & banking:2; IT services & consulting:3; Gaming:1; Automotive:1"),
        education=w("bachelor:5; master:2; vocational:2; none:1"),
        fields=["Computer Science", "Information Systems", "Mathematics", "Economics"],
        sizes="tech", work=w("remote:3; hybrid:6; office:1"), employment=w("employee:9; freelancer:1"),
        salary=1.15, globalized=0.5, intensity=0.8,
        tools=w("ChatGPT:7; GitHub Copilot:5; Claude:3; Gemini:2; Cursor:1"),
        uses=["generating test cases from requirements", "writing automated tests", "creating test data",
              "writing clear bug reports", "spotting gaps in requirements"],
        attitudes=w("enthusiast:2; pragmatist:5; cautious:2; skeptic:1.5"),
        concerns=w("accuracy:3; job:2.5; deskilling:2; security:1"),
        wins=["generated 80 edge-case test scenarios from a spec in ten minutes"],
        fails=["AI-written tests only checked the happy path and gave false confidence"]),
    dict(
        key="it_support", label="IT support / system administrator", weight=2, female=0.25, min_age=19,
        titles=dict(junior=["IT Support Technician"], mid=["IT Support Specialist", "System Administrator"],
                    senior=["Senior System Administrator"], lead=["IT Team Lead"], head=["IT Manager"]),
        industries=w("Manufacturing:2; Public sector:2; Healthcare:1; Education:1; IT services & consulting:2; Retail:1; Law & accounting firms:1"),
        education=w("vocational:5; bachelor:4; none:1; secondary:1"),
        fields=["Information Technology", "Computer Science", "Electronics"],
        sizes="mixed", work=w("remote:1; hybrid:4; office:5"), employment=w("employee:10; freelancer:1"),
        salary=1.0, globalized=0.2, intensity=0.7,
        tools=w("ChatGPT:7; Microsoft Copilot:6; Gemini:2; Claude:2"),
        uses=["troubleshooting user issues", "writing PowerShell scripts", "writing knowledge-base articles",
              "drafting outage announcements", "understanding cryptic error codes"],
        attitudes=w("enthusiast:2; pragmatist:6; cautious:2; skeptic:1.5"),
        concerns=w("security:3; privacy:3; accuracy:2; job:1"),
        wins=["wrote a PowerShell script that automated onboarding for new laptops"],
        fails=["followed a suggested registry fix that made things worse"]),
    dict(
        key="security", label="Cybersecurity specialist", weight=1.2, female=0.2, min_age=22, max_years=25,
        titles=dict(junior=["SOC Analyst"], mid=["Security Analyst", "Security Engineer"],
                    senior=["Senior Security Consultant", "Senior Security Engineer"], lead=["Security Team Lead"],
                    head=["Head of Information Security"]),
        freelance_title="Independent Security Consultant",
        industries=w("FinTech & banking:2; IT services & consulting:3; Software / SaaS:2; Public sector:1; Energy:1"),
        education=w("bachelor:5; master:4; vocational:1"),
        fields=["Computer Science", "Information Security", "Mathematics"],
        sizes="corp", work=w("remote:2; hybrid:6; office:2"), employment=w("employee:9; freelancer:1"),
        salary=1.45, globalized=0.5, intensity=0.75,
        tools=w("ChatGPT:5; Claude:4; Microsoft Security Copilot:3; GitHub Copilot:2; local open-source models (Ollama):2; Gemini:1"),
        uses=["summarising threat intelligence reports", "analysing suspicious scripts and logs", "writing detection rules",
              "drafting security awareness material", "writing audit and pentest reports"],
        attitudes=w("enthusiast:1; pragmatist:4; cautious:4; skeptic:2"),
        concerns=w("privacy:4; security:3; accuracy:3; dependence:2; misinfo:1"),
        wins=["decoded an obfuscated phishing script in minutes"],
        fails=["caught a colleague pasting internal logs into a public chatbot"]),
    dict(
        key="product_manager", label="Product manager", weight=4, female=0.45, min_age=23, max_years=20,
        titles=dict(junior=["Associate Product Manager"], mid=["Product Manager", "Product Owner"],
                    senior=["Senior Product Manager"], lead=["Group Product Manager", "Lead Product Manager"],
                    head=["Head of Product", "VP Product"]),
        freelance_title="Freelance Product Consultant",
        industries=w("Software / SaaS:5; FinTech & banking:2; E-commerce & retail:2; HealthTech:1; Telecommunications:1; Media:1"),
        education=w("bachelor:3; master:6; phd:0.3"),
        fields=["Business Administration", "Computer Science", "Economics", "Industrial Engineering", "Design"],
        sizes="tech", work=w("remote:2; hybrid:7; office:1"), employment=w("employee:9; freelancer:0.7; founder:0.5"),
        salary=1.45, globalized=0.4, intensity=0.9,
        tools=w("ChatGPT:8; Claude:6; Notion AI:3; Perplexity:3; Gemini:2; Microsoft Copilot:2; Miro AI:1; Lovable:1; v0:1; Gamma:1"),
        uses=["writing PRDs and user stories", "synthesising user interview notes", "competitor research",
              "summarising meetings", "building clickable prototypes", "drafting release notes", "prioritisation brainstorming"],
        attitudes=w("enthusiast:4; pragmatist:5; cautious:1.5; skeptic:0.7"),
        concerns=w("accuracy:3; privacy:2; bland:2; deskilling:1.5; job:1"),
        wins=["clustered 60 user interviews into themes in one evening",
              "built a working prototype to test with users before involving engineering"],
        fails=["the AI summary missed the one critical complaint in the interviews",
               "a stakeholder said my PRD 'read like ChatGPT' and they were right"]),
    dict(
        key="ux_designer", label="UX / product designer", weight=3, female=0.55, min_age=21, max_years=22,
        titles=dict(junior=["Junior UX Designer"], mid=["UX/UI Designer", "Product Designer"],
                    senior=["Senior Product Designer"], lead=["Design Lead"], head=["Head of Design"]),
        freelance_title="Freelance UX Designer",
        industries=w("Software / SaaS:4; Digital agency:3; E-commerce & retail:2; FinTech & banking:1; Media:1"),
        education=w("bachelor:5; master:4; vocational:1"),
        fields=["Interaction Design", "Graphic Design", "Psychology", "Human-Computer Interaction", "Media Design"],
        sizes="tech", work=w("remote:3; hybrid:6; office:1"), employment=w("employee:7; freelancer:3"),
        salary=1.15, globalized=0.4, intensity=0.75,
        tools=w("ChatGPT:7; Figma AI:6; Midjourney:4; Claude:3; Adobe Firefly:2; Lovable:1; v0:1; Perplexity:1"),
        uses=["writing UX microcopy", "summarising user research", "generating moodboards and visual concepts",
              "quick prototyping", "creating realistic placeholder content", "accessibility checks"],
        attitudes=w("enthusiast:2; pragmatist:5; cautious:3; skeptic:1.5"),
        concerns=w("copyright:3; bland:3; job:2; deskilling:2; accuracy:1"),
        wins=["tested three prototype directions with users in the time one used to take"],
        fails=["AI-generated screens looked polished but ignored basic usability"]),
    dict(
        key="graphic_designer", label="Graphic designer", weight=2.5, female=0.55, min_age=20,
        titles=dict(junior=["Junior Graphic Designer"], mid=["Graphic Designer"], senior=["Senior Graphic Designer"],
                    lead=["Art Director"], head=["Creative Director"]),
        freelance_title="Freelance Graphic Designer",
        industries=w("Advertising agency:4; Publishing:1; E-commerce & retail:1; Consumer goods:1; Media:1; Events:1"),
        education=w("bachelor:6; master:2; vocational:2"),
        fields=["Graphic Design", "Visual Communication", "Fine Arts", "Illustration"],
        sizes="agency", work=w("remote:3; hybrid:5; office:2"), employment=w("employee:5; freelancer:5"),
        salary=0.95, globalized=0.2, intensity=0.7,
        tools=w("Adobe Photoshop Generative Fill:8; Adobe Firefly:5; Midjourney:6; ChatGPT:5; Canva Magic Studio:3; Ideogram:1.5; Krea:1"),
        uses=["extending and retouching images", "generating concept art and moodboards", "creating mockups quickly",
              "removing backgrounds", "writing briefs and client emails", "making variations for social media formats"],
        attitudes=w("enthusiast:1.5; pragmatist:4; cautious:3; skeptic:3"),
        concerns=w("copyright:5; job:4; bland:2; env:1; pay:2"),
        wins=["Generative Fill saved a product shoot where the background was unusable",
              "showed a client twenty concept directions in the first meeting instead of three"],
        fails=["a client rejected a concept because it 'looked like AI'",
               "a client asked why they should pay my rate if 'AI can do it'"]),
    dict(
        key="marketing", label="Marketing specialist / manager", weight=6, female=0.6, min_age=21,
        titles=dict(junior=["Marketing Assistant", "Junior Marketing Specialist"], mid=["Marketing Manager", "Digital Marketing Manager", "Performance Marketing Specialist"],
                    senior=["Senior Marketing Manager", "Brand Manager"], lead=["Marketing Team Lead"],
                    head=["Head of Marketing", "CMO"]),
        freelance_title="Freelance Marketing Consultant",
        industries=w("Consumer goods:2; Software / SaaS:2; E-commerce & retail:2; Tourism & hospitality:1; FinTech & banking:1; "
                     "Advertising agency:2; Manufacturing:1; Non-profit:0.5"),
        education=w("bachelor:5; master:5; vocational:0.5"),
        fields=["Marketing", "Business Administration", "Communication Studies", "Media Studies", "Economics"],
        sizes="mixed", work=w("remote:2; hybrid:6; office:2"), employment=w("employee:8; freelancer:2"),
        salary=1.1, globalized=0.2, intensity=0.9,
        tools=w("ChatGPT:9; Canva Magic Studio:5; Claude:4; Gemini:3; Perplexity:3; Midjourney:3; Jasper:1.5; "
                "Microsoft Copilot:2; HubSpot Breeze AI:1.5; DeepL:2"),
        uses=["writing social media posts", "drafting blog articles", "ad copy variations", "SEO keyword research",
              "campaign brainstorming", "localising campaigns into other languages", "creating visuals",
              "analysing campaign performance", "writing newsletters"],
        attitudes=w("enthusiast:4; pragmatist:5; cautious:1.5; skeptic:1"),
        concerns=w("bland:4; accuracy:2; copyright:2; job:2; privacy:1; misinfo:0.5"),
        wins=["localised a whole campaign into six languages in one day",
              "tested twenty email subject lines instead of three"],
        fails=["we published a blog post with a statistic the AI made up",
               "our AI-written LinkedIn posts got called out as generic by a customer"]),
    dict(
        key="content_writer", label="Content writer / copywriter", weight=3, female=0.6, min_age=21,
        titles=dict(junior=["Junior Copywriter", "Content Writer"], mid=["Copywriter", "Content Writer", "Content Marketing Specialist"],
                    senior=["Senior Copywriter"], lead=["Content Lead"], head=["Head of Content"]),
        freelance_title="Freelance Copywriter",
        industries=w("Advertising agency:3; Software / SaaS:2; Media:2; E-commerce & retail:1; Publishing:1"),
        education=w("bachelor:6; master:4"),
        fields=["Journalism", "English Literature", "Communication Studies", "Linguistics", "Marketing", "History"],
        sizes="agency", work=w("remote:4; hybrid:5; office:1"), employment=w("employee:5; freelancer:5"),
        salary=0.95, globalized=0.3, intensity=0.85,
        tools=w("ChatGPT:8; Claude:7; Grammarly:4; DeepL:4; Perplexity:3; Gemini:2; Jasper:1; Surfer SEO:1"),
        uses=["outlining articles", "getting past the blank page", "tightening and editing drafts", "background research",
              "headline variations", "rewriting for different audiences", "SEO optimisation", "proofreading"],
        attitudes=w("enthusiast:1.5; pragmatist:4; cautious:3; skeptic:3"),
        concerns=w("job:5; bland:4; pay:3; copyright:2; accuracy:2"),
        wins=["turned a 40-page whitepaper into ten decent posts in a day",
              "AI feedback helped me cut a bloated draft by a third"],
        fails=["lost a retainer client who decided to 'just use ChatGPT'",
               "the AI rewrite flattened my client's tone of voice completely"]),
    dict(
        key="social_media", label="Social media manager", weight=2, female=0.7, min_age=20, max_years=15,
        titles=dict(junior=["Social Media Coordinator"], mid=["Social Media Manager", "Community Manager"],
                    senior=["Senior Social Media Manager"], lead=["Social Media Lead"], head=["Head of Social"]),
        freelance_title="Freelance Social Media Manager",
        industries=w("Advertising agency:3; Consumer goods:2; Fashion:1; Tourism & hospitality:1; Media:1; Sports:0.5"),
        education=w("bachelor:6; master:2; vocational:1; none:1"),
        fields=["Communication Studies", "Marketing", "Media Studies", "Journalism"],
        sizes="agency", work=w("remote:3; hybrid:5; office:2"), employment=w("employee:6; freelancer:4"),
        salary=0.85, globalized=0.2, intensity=0.9,
        tools=w("ChatGPT:8; Canva Magic Studio:6; CapCut:5; Opus Clip:2; Midjourney:2; Claude:2; Gemini:2"),
        uses=["writing captions", "planning content calendars", "cutting long videos into clips", "hooks and hashtags",
              "replying to comments", "trend research"],
        attitudes=w("enthusiast:4; pragmatist:5; cautious:1; skeptic:1"),
        concerns=w("bland:4; job:2; copyright:2; misinfo:1"),
        wins=["planned a month of posts on a Sunday afternoon"],
        fails=["an AI caption used a trending phrase that turned out to be offensive"]),
    dict(
        key="sales", label="Sales representative / account manager", weight=4, female=0.35, min_age=21,
        titles=dict(junior=["Sales Development Representative"], mid=["Account Executive", "Account Manager", "Inside Sales Representative"],
                    senior=["Senior Account Executive", "Key Account Manager"], lead=["Sales Team Lead"],
                    head=["Head of Sales", "Sales Director"]),
        freelance_title="Independent Sales Agent",
        industries=w("Software / SaaS:4; Manufacturing:2; Logistics:1; Telecommunications:1; Medical devices:1; Consumer goods:1; Energy:1"),
        education=w("bachelor:5; master:2; vocational:2; secondary:1"),
        fields=["Business Administration", "Economics", "Marketing", "Engineering"],
        sizes="corp", work=w("remote:2; hybrid:6; office:2"), employment=w("employee:9; freelancer:1"),
        salary=1.2, globalized=0.2, intensity=0.75,
        tools=w("ChatGPT:8; Microsoft Copilot:4; Salesforce Agentforce:1.5; HubSpot Breeze AI:1.5; Gong:2; Claude:2; Gemini:2; "
                "Perplexity:2; Fireflies.ai:2"),
        uses=["writing outreach emails", "researching prospects", "preparing for calls", "turning call notes into CRM entries",
              "drafting proposals", "practising objection handling", "translating emails"],
        attitudes=w("enthusiast:3; pragmatist:6; cautious:1.5; skeptic:1"),
        concerns=w("bland:3; accuracy:2; privacy:2; job:1"),
        wins=["prospect research that took an hour now takes ten minutes"],
        fails=["sent an AI-drafted email that got the client's company name wrong"]),
    dict(
        key="customer_support", label="Customer support / customer success", weight=3, female=0.6, min_age=19,
        titles=dict(junior=["Customer Support Agent"], mid=["Customer Support Specialist", "Customer Success Manager"],
                    senior=["Senior Support Specialist"], lead=["Support Team Lead"], head=["Head of Customer Support"]),
        industries=w("Software / SaaS:3; E-commerce & retail:3; Telecommunications:2; Travel:1; FinTech & banking:1; Utilities:1"),
        education=w("secondary:2; vocational:2; bachelor:5; master:1"),
        fields=["Business Administration", "Languages", "Communication Studies", "Tourism"],
        sizes="corp", work=w("remote:3; hybrid:5; office:2"), employment=w("employee:10"),
        salary=0.8, globalized=0.1, intensity=0.8,
        tools=w("ChatGPT:6; Zendesk AI:4; Intercom Fin:3; DeepL:4; Microsoft Copilot:2; internal company AI assistant:3; Gemini:1; Claude:1"),
        uses=["drafting replies to tickets", "translating customer messages", "summarising long ticket threads",
              "writing help-centre articles", "softening replies to angry customers", "tagging and routing tickets"],
        attitudes=w("enthusiast:2; pragmatist:5; cautious:2; skeptic:2"),
        concerns=w("job:4; accuracy:3; privacy:2; human:2"),
        wins=["can now answer tickets in Italian and Dutch without waiting for a colleague"],
        fails=["the chatbot promised a customer a refund we don't offer and I had to clean it up"]),
    dict(
        key="hr", label="HR / recruiter", weight=3.5, female=0.75, min_age=21,
        titles=dict(junior=["HR Assistant", "Junior Recruiter"], mid=["Recruiter", "HR Generalist", "Talent Acquisition Specialist"],
                    senior=["HR Business Partner", "Senior Talent Acquisition Partner"], lead=["HR Team Lead"],
                    head=["HR Manager", "Head of People"]),
        freelance_title="Freelance Recruiter",
        industries=w("Software / SaaS:2; Manufacturing:2; Recruitment agency:2; Retail:1; FinTech & banking:1; Healthcare:1; Logistics:1"),
        education=w("bachelor:5; master:4; vocational:1"),
        fields=["Psychology", "Business Administration", "Human Resources Management", "Law", "Sociology"],
        sizes="corp", work=w("remote:1; hybrid:7; office:2"), employment=w("employee:9; freelancer:1"),
        salary=1.0, globalized=0.1, intensity=0.7,
        tools=w("ChatGPT:8; Microsoft Copilot:5; LinkedIn Recruiter AI:3; Claude:2; Gemini:2; DeepL:2"),
        uses=["writing job descriptions", "drafting interview questions", "writing internal announcements",
              "creating onboarding materials", "drafting HR policies", "polishing rejection emails"],
        attitudes=w("enthusiast:2; pragmatist:5; cautious:3; skeptic:1.5"),
        concerns=w("bias:4; privacy:4; ai_act:2; accuracy:2; human:2"),
        wins=["rewrote all our job ads in a week and applications went up"],
        fails=["noticed an AI-written job ad used noticeably masculine language"]),
    dict(
        key="finance", label="Accountant / financial analyst", weight=4.5, female=0.5, min_age=21,
        titles=dict(junior=["Junior Accountant", "Accounting Assistant"], mid=["Accountant", "Financial Analyst", "FP&A Analyst"],
                    senior=["Senior Financial Analyst", "Senior Accountant"], lead=["Financial Controller", "Finance Manager"],
                    head=["Head of Finance", "CFO"]),
        freelance_title="Self-employed Accountant",
        industries=w("Banking:2; Insurance:1; Accounting firm:2; Manufacturing:2; Retail:1; Real estate:1; Energy:1; Software / SaaS:1"),
        education=w("bachelor:5; master:4; vocational:2"),
        fields=["Accounting", "Finance", "Economics", "Business Administration"],
        sizes="corp", work=w("remote:1; hybrid:6; office:3"), employment=w("employee:9; freelancer:1"),
        salary=1.15, globalized=0.1, intensity=0.6,
        tools=w("Microsoft Copilot:6; ChatGPT:7; Claude:3; Gemini:2; DeepL:1; Perplexity:1"),
        uses=["writing Excel formulas and macros", "explaining accounting standards (IFRS)", "drafting variance commentary",
              "summarising annual reports", "building financial models faster", "writing emails to auditors",
              "reconciliation scripts in Python"],
        attitudes=w("enthusiast:1.5; pragmatist:5; cautious:3; skeptic:2"),
        concerns=w("accuracy:5; privacy:4; job:2; policy:1"),
        wins=["month-end commentary that took a day now takes a couple of hours"],
        fails=["an AI-built formula silently summed the wrong range and it ended up in a board deck"]),
    dict(
        key="consultant", label="Management / IT consultant", weight=3.5, female=0.45, min_age=22,
        titles=dict(junior=["Business Analyst", "Junior Consultant"], mid=["Consultant"], senior=["Senior Consultant"],
                    lead=["Manager", "Principal Consultant"], head=["Partner", "Director"]),
        freelance_title="Independent Consultant",
        industries=w("Management consulting:4; IT consulting:3; Audit & advisory (Big Four):2; Public sector consulting:1"),
        education=w("master:7; bachelor:2; phd:1"),
        fields=["Business Administration", "Economics", "Industrial Engineering", "Computer Science", "Law"],
        sizes="corp", work=w("remote:1; hybrid:8; office:1"), employment=w("employee:8; freelancer:2"),
        salary=1.45, globalized=0.2, intensity=0.9,
        tools=w("ChatGPT:7; Microsoft Copilot:5; Claude:5; Perplexity:4; internal company AI assistant:4; Gemini:2; NotebookLM:2; Gamma:1"),
        uses=["desk research", "drafting slide storylines", "synthesising interview notes", "writing proposals",
              "summarising long reports", "Excel analysis", "preparing workshop material"],
        attitudes=w("enthusiast:3; pragmatist:6; cautious:1.5; skeptic:0.7"),
        concerns=w("accuracy:3; privacy:3; deskilling:2; job:2; bland:1"),
        wins=["got up to speed on a new industry over a weekend before a client kick-off"],
        fails=["a slide went to a client with a market figure nobody could source afterwards"]),
    dict(
        key="project_manager", label="Project manager", weight=3.5, female=0.45, min_age=23,
        titles=dict(junior=["Project Coordinator"], mid=["Project Manager"], senior=["Senior Project Manager"],
                    lead=["Programme Manager"], head=["Head of PMO", "Head of Delivery"]),
        freelance_title="Freelance Project Manager",
        industries=w("IT services & consulting:2; Construction:2; Pharmaceuticals:1; Manufacturing:2; Public sector:1; "
                     "Telecommunications:1; Events:0.5; Energy:1"),
        education=w("bachelor:5; master:4; vocational:1"),
        fields=["Business Administration", "Engineering", "Computer Science", "Economics", "Architecture"],
        sizes="corp", work=w("remote:1; hybrid:7; office:2"), employment=w("employee:8; freelancer:2"),
        salary=1.2, globalized=0.1, intensity=0.75,
        tools=w("Microsoft Copilot:7; ChatGPT:7; Notion AI:2; Otter.ai:1; Fireflies.ai:1; Claude:2; Gemini:2; Atlassian Intelligence:2"),
        uses=["meeting summaries and action items", "status reports", "risk registers", "stakeholder emails",
              "first drafts of project plans", "translating messages for international teams"],
        attitudes=w("enthusiast:2; pragmatist:6; cautious:2; skeptic:1"),
        concerns=w("accuracy:3; privacy:3; policy:2; bland:1"),
        wins=["Teams meeting recaps mean I finally stopped taking notes during calls"],
        fails=["an automatic recap assigned an action item to the wrong person"]),
    dict(
        key="business_analyst", label="Business analyst", weight=2, female=0.5, min_age=22, max_years=28,
        titles=dict(junior=["Junior Business Analyst"], mid=["Business Analyst"], senior=["Senior Business Analyst"],
                    lead=["Lead Business Analyst"], head=["Head of Business Analysis"]),
        industries=w("Banking:2; Insurance:2; IT services & consulting:2; Public sector:1; Telecommunications:1; Retail:1"),
        education=w("bachelor:5; master:5"),
        fields=["Business Informatics", "Economics", "Business Administration", "Computer Science"],
        sizes="corp", work=w("remote:2; hybrid:7; office:1"), employment=w("employee:9; freelancer:1"),
        salary=1.2, globalized=0.2, intensity=0.8,
        tools=w("ChatGPT:7; Microsoft Copilot:5; Claude:3; Gemini:2; Miro AI:1"),
        uses=["writing requirements documents", "process mapping", "SQL queries", "user stories", "summarising workshops",
              "test scenarios"],
        attitudes=w("enthusiast:2; pragmatist:6; cautious:2; skeptic:1"),
        concerns=w("accuracy:3; privacy:3; job:2; deskilling:1"),
        wins=["turned a messy two-hour workshop recording into clean requirements the same day"],
        fails=["the AI 'filled gaps' in requirements with assumptions nobody had agreed on"]),
    dict(
        key="operations", label="Operations / logistics manager", weight=2.5, female=0.4, min_age=22,
        titles=dict(junior=["Operations Coordinator", "Logistics Coordinator"], mid=["Operations Manager", "Supply Chain Analyst", "Logistics Manager"],
                    senior=["Senior Supply Chain Manager"], lead=["Operations Team Lead"], head=["Head of Operations"]),
        industries=w("Logistics:3; Manufacturing:3; Retail:2; Food production:1; Automotive:1; E-commerce & retail:1"),
        education=w("bachelor:5; master:3; vocational:3"),
        fields=["Logistics", "Business Administration", "Industrial Engineering", "Economics"],
        sizes="corp", work=w("remote:0.5; hybrid:5; office:5"), employment=w("employee:10"),
        salary=1.05, globalized=0.1, intensity=0.55,
        tools=w("ChatGPT:7; Microsoft Copilot:6; DeepL:3; Gemini:2; Claude:1"),
        uses=["Excel analysis of shipments and inventory", "writing SOPs", "supplier emails in other languages",
              "summarising contracts", "shift planning"],
        attitudes=w("enthusiast:1.5; pragmatist:6; cautious:2; skeptic:1.5"),
        concerns=w("accuracy:3; privacy:2; cost:1; job:1"),
        wins=["writes supplier emails in Polish and Czech that actually get answered"],
        fails=["a demand forecast from ChatGPT was nonsense because it ignored seasonality"]),
    dict(
        key="office_manager", label="Office manager / executive assistant", weight=2.5, female=0.85, min_age=20,
        titles=dict(junior=["Administrative Assistant", "Team Assistant"], mid=["Office Manager", "Executive Assistant"],
                    senior=["Senior Executive Assistant"], lead=["Office Manager"], head=["Head of Office Management"]),
        industries=w("Law firm:1; Manufacturing:2; Software / SaaS:1; Real estate:1; Accounting firm:1; Healthcare:1; Non-profit:1"),
        education=w("vocational:5; bachelor:4; secondary:2"),
        fields=["Office Administration", "Business Administration", "Languages"],
        sizes="mixed", work=w("remote:0.5; hybrid:4; office:6"), employment=w("employee:10"),
        salary=0.85, globalized=0.0, intensity=0.6,
        tools=w("Microsoft Copilot:7; ChatGPT:7; DeepL:4; Gemini:2; Grammarly:2"),
        uses=["drafting emails and letters", "summarising long email threads", "meeting minutes", "planning travel and events",
              "formatting documents", "translating correspondence"],
        attitudes=w("enthusiast:3; pragmatist:6; cautious:2; skeptic:1"),
        concerns=w("privacy:3; accuracy:2; job:2; policy:2"),
        wins=["planned a three-city business trip with all options compared in twenty minutes"],
        fails=["Copilot summarised the wrong version of a document before a board meeting"]),
    dict(
        key="lawyer", label="Lawyer / legal counsel", weight=3, female=0.5, min_age=25,
        titles=dict(junior=["Junior Associate", "Trainee Lawyer"], mid=["Associate", "Legal Counsel"],
                    senior=["Senior Associate", "Senior Legal Counsel"], lead=["Counsel"], head=["Partner", "General Counsel"]),
        freelance_title="Self-employed Lawyer",
        industries=w("Law firm:6; In-house legal (tech company):2; In-house legal (bank or insurer):2; Public administration:1"),
        education=w("master:8; phd:2"),
        fields=["Law"],
        sizes="corp", work=w("remote:0.5; hybrid:7; office:3"), employment=w("employee:8; freelancer:1.5"),
        salary=1.6, globalized=0.1, intensity=0.6,
        tools=w("ChatGPT:5; Harvey:3; Legora:2; Microsoft Copilot:4; Claude:3; DeepL:5; internal company AI assistant:2; CoCounsel:1"),
        uses=["first drafts of contracts and clauses", "summarising judgments", "spotting risky clauses in contracts",
              "translating legal documents", "drafting client emails", "legal research (always verified)",
              "due diligence document review"],
        attitudes=w("enthusiast:1.5; pragmatist:4; cautious:4; skeptic:2"),
        concerns=w("accuracy:5; privacy:5; liability:2; ai_act:1.5; deskilling:2"),
        wins=["a first-pass review of 300 contracts took days instead of weeks",
              "got a solid first draft of a data processing agreement in minutes"],
        fails=["a colleague nearly cited a judgment that doesn't exist",
               "the translation of a German clause subtly changed its legal meaning"]),
    dict(
        key="compliance", label="Compliance / risk specialist", weight=1.5, female=0.6, min_age=23,
        titles=dict(junior=["Compliance Analyst"], mid=["Compliance Officer", "Risk Analyst"], senior=["Senior Compliance Manager"],
                    lead=["Compliance Team Lead"], head=["Head of Compliance", "Chief Risk Officer"]),
        industries=w("Banking:3; Insurance:2; FinTech & banking:2; Pharmaceuticals:1; Energy:1"),
        education=w("master:7; bachelor:3"),
        fields=["Law", "Economics", "Finance", "Business Administration"],
        sizes="corp", work=w("hybrid:7; office:3"), employment=w("employee:10"),
        salary=1.3, globalized=0.1, intensity=0.55,
        tools=w("Microsoft Copilot:5; internal company AI assistant:4; ChatGPT:4; DeepL:3; Claude:2"),
        uses=["summarising new regulation (DORA, AI Act, NIS2)", "drafting internal policies", "mapping controls",
              "preparing training material", "reviewing documents"],
        attitudes=w("enthusiast:1; pragmatist:5; cautious:4; skeptic:1.5"),
        concerns=w("accuracy:4; privacy:4; ai_act:3; liability:2"),
        wins=["mapped DORA requirements to our existing controls in a fraction of the time"],
        fails=["an AI summary of a regulation left out an important exemption"]),
    dict(
        key="teacher", label="School teacher", weight=4, female=0.7, min_age=23,
        titles=dict(junior=["Trainee Teacher"], mid=["Secondary School Teacher", "Primary School Teacher", "Vocational School Teacher",
                                                     "English Teacher", "Maths Teacher", "Biology Teacher", "History Teacher"],
                    senior=["Senior Teacher"], lead=["Head of Department"], head=["Deputy Head Teacher"]),
        freelance_title="Private Tutor",
        industries=w("Public secondary school:6; Primary school:2; Vocational school:2; Private school:1; Language school:1"),
        education=w("master:6; bachelor:4"),
        fields=["Education", "English", "Mathematics", "Biology", "History", "German", "Physics", "Chemistry", "Geography"],
        sizes="school", work=w("office:9; hybrid:1"), employment=w("employee:10; freelancer:0.5"),
        salary=1.0, globalized=0.0, intensity=0.55,
        tools=w("ChatGPT:8; Gemini:3; Microsoft Copilot:3; Canva Magic Studio:3; MagicSchool:2; DeepL:2; Claude:2; fobizz:1"),
        uses=["lesson planning", "creating worksheets and quizzes", "differentiating material for different levels",
              "writing letters to parents", "feedback on essays (carefully)", "generating example texts", "writing rubrics"],
        attitudes=w("enthusiast:2; pragmatist:4; cautious:4; skeptic:2"),
        concerns=w("cheating:5; deskilling:3; accuracy:2; privacy:2; human:1"),
        wins=["made three versions of one worksheet for different levels in fifteen minutes",
              "turned my lesson notes into a quiz on the train to school"],
        fails=["half the class handed in essays with the same ChatGPT structure",
               "a generated history worksheet had a wrong date I only noticed in class"]),
    dict(
        key="researcher", label="University researcher / lecturer", weight=3.5, female=0.45, min_age=24,
        titles=dict(junior=["PhD Candidate", "Research Assistant"], mid=["Postdoctoral Researcher", "Lecturer"],
                    senior=["Assistant Professor", "Senior Lecturer"], lead=["Associate Professor"],
                    head=["Professor", "Research Group Leader"]),
        industries=w("University:8; Research institute:3"),
        education=w("phd:7; master:3"),
        fields=["Biology", "Computer Science", "Economics", "Psychology", "Physics", "Sociology", "Chemistry",
                "Linguistics", "Political Science", "Environmental Science", "Medicine"],
        sizes="university", work=w("remote:1; hybrid:7; office:2"), employment=w("employee:10"),
        salary=1.05, globalized=0.3, intensity=0.75,
        tools=w("ChatGPT:7; Claude:5; DeepL:5; Elicit:2; Consensus:2; Perplexity:2; Grammarly:2; GitHub Copilot:3; NotebookLM:3; DeepL Write:2"),
        uses=["literature search and summarising papers", "editing the English in manuscripts", "writing and debugging R/Python code",
              "first drafts of grant proposals", "preparing lecture slides", "translating", "creating exam questions"],
        attitudes=w("enthusiast:2; pragmatist:5; cautious:3; skeptic:2"),
        concerns=w("accuracy:4; cheating:3; deskilling:2; copyright:2; env:2; dependence:2"),
        wins=["polished the English of a paper that was then accepted with minor revisions",
              "cut the time for a literature scan for a grant proposal in half"],
        fails=["it gave me three references that looked perfect and didn't exist",
               "caught a student thesis chapter clearly written by a chatbot"]),
    dict(
        key="physician", label="Physician", weight=1.5, female=0.5, min_age=27,
        titles=dict(junior=["Resident Physician"], mid=["General Practitioner", "Specialist Physician", "Radiologist",
                                                        "Paediatrician", "Anaesthesiologist"],
                    senior=["Senior Physician", "Consultant"], lead=["Senior Consultant"], head=["Chief Physician"]),
        freelance_title="GP in private practice",
        industries=w("Public hospital:5; Private practice:3; Private clinic:2"),
        education=w("medicine:9; phd:1"),
        fields=["Medicine"],
        sizes="hospital", work=w("office:10"), employment=w("employee:7; freelancer:3"),
        salary=2.0, globalized=0.2, intensity=0.45,
        tools=w("ChatGPT:5; OpenEvidence:3; AI medical scribe:4; DeepL:3; Microsoft Copilot:2; Claude:2"),
        uses=["clinical documentation with an AI scribe", "drafting patient letters and discharge summaries",
              "checking latest guidelines and studies", "translating patient information", "preparing talks"],
        attitudes=w("enthusiast:1.5; pragmatist:3; cautious:5; skeptic:2"),
        concerns=w("accuracy:5; privacy:5; liability:3; human:2; ai_act:1"),
        wins=["the AI scribe gives me back almost an hour a day of documentation",
              "explained a complex diagnosis to a patient in plain Turkish via translation"],
        fails=["a draft discharge letter listed a medication the patient never received"]),
    dict(
        key="nurse", label="Nurse", weight=1.2, female=0.85, min_age=21,
        titles=dict(junior=["Nurse"], mid=["Registered Nurse", "Intensive Care Nurse"], senior=["Senior Nurse"],
                    lead=["Ward Manager"], head=["Head of Nursing"]),
        industries=w("Public hospital:6; Private clinic:2; Care home:2; Home care service:1"),
        education=w("bachelor:5; vocational:5"),
        fields=["Nursing"],
        sizes="hospital", work=w("office:10"), employment=w("employee:10"),
        salary=0.85, globalized=0.0, intensity=0.35,
        tools=w("ChatGPT:8; DeepL:3; Gemini:2; Microsoft Copilot:1"),
        uses=["writing patient information in plain language", "shift and rota planning", "studying for certifications",
              "translating instructions for patients", "drafting emails and incident reports"],
        attitudes=w("enthusiast:1.5; pragmatist:5; cautious:3; skeptic:2"),
        concerns=w("privacy:3; accuracy:3; human:3; deskilling:1"),
        wins=["made a simple aftercare leaflet in Arabic and Ukrainian for our patients"],
        fails=["a colleague trusted a dosage conversion from ChatGPT without checking"]),
    dict(
        key="psychologist", label="Psychologist / psychotherapist", weight=1, female=0.75, min_age=25,
        titles=dict(mid=["Psychologist", "Psychotherapist", "Clinical Psychologist"], senior=["Senior Clinical Psychologist"],
                    head=["Head of Psychology Service"]),
        freelance_title="Psychotherapist in private practice",
        industries=w("Private practice:5; Public hospital:2; Counselling service:1"),
        education=w("master:8; phd:2"),
        fields=["Psychology"],
        sizes="practice", work=w("office:6; hybrid:4"), employment=w("employee:4; freelancer:6"),
        salary=1.05, globalized=0.0, intensity=0.35,
        tools=w("ChatGPT:7; Claude:3; DeepL:2"),
        uses=["writing psychoeducation handouts", "admin emails and invoices", "structuring reports without identifying details",
              "keeping up with research", "texts for the practice website"],
        attitudes=w("enthusiast:0.7; pragmatist:3; cautious:4; skeptic:4"),
        concerns=w("privacy:5; human:4; accuracy:2; deskilling:2"),
        wins=["created clear handouts on sleep hygiene in an evening"],
        fails=["a client told me they had been using a chatbot as their therapist between sessions"]),
    dict(
        key="pharmacist", label="Pharmacist", weight=0.8, female=0.7, min_age=24,
        titles=dict(mid=["Pharmacist"], senior=["Senior Pharmacist"], head=["Pharmacy Manager"]),
        freelance_title="Pharmacy Owner",
        industries=w("Pharmacy:6; Public hospital:2"),
        education=w("master:9; phd:1"),
        fields=["Pharmacy"],
        sizes="practice", work=w("office:10"), employment=w("employee:8; freelancer:2"),
        salary=1.15, globalized=0.0, intensity=0.35,
        tools=w("ChatGPT:6; DeepL:2; Microsoft Copilot:2"),
        uses=["patient leaflets in plain language", "staff training material", "ordering and inventory emails",
              "first look at interactions before checking official databases"],
        attitudes=w("enthusiast:1; pragmatist:4; cautious:4; skeptic:2"),
        concerns=w("accuracy:5; liability:3; privacy:2"),
        wins=["made a clear weekly pill-schedule template for elderly customers"],
        fails=["it got an interaction wrong that our official database flagged immediately"]),
    dict(
        key="journalist", label="Journalist / editor", weight=2, female=0.5, min_age=21,
        titles=dict(junior=["Junior Reporter", "Trainee Journalist"], mid=["Journalist", "Reporter", "Online Editor"],
                    senior=["Senior Editor"], lead=["Desk Editor"], head=["Editor-in-Chief"]),
        freelance_title="Freelance Journalist",
        industries=w("Newspaper:3; Online media:3; Public broadcaster:2; Magazine:1; News agency:1"),
        education=w("bachelor:4; master:6"),
        fields=["Journalism", "Political Science", "History", "Communication Studies", "Economics", "Literature"],
        sizes="agency", work=w("remote:2; hybrid:6; office:2"), employment=w("employee:6; freelancer:4"),
        salary=0.95, globalized=0.1, intensity=0.6,
        tools=w("ChatGPT:6; AI transcription (Whisper-based):6; DeepL:5; Perplexity:3; Claude:3; Gemini:2; NotebookLM:2; Otter.ai:1"),
        uses=["transcribing interviews", "summarising long reports", "headline and teaser variations", "translating sources",
              "starting points for research (always verified)", "SEO metadata"],
        attitudes=w("enthusiast:1; pragmatist:3; cautious:4; skeptic:4"),
        concerns=w("accuracy:5; misinfo:4; job:3; copyright:3; dependence:2; bland:2"),
        wins=["transcription alone saves me half a day per long interview"],
        fails=["an AI summary attributed a quote to the wrong politician"]),
    dict(
        key="translator", label="Translator / localisation specialist", weight=2, female=0.7, min_age=22,
        titles=dict(junior=["Junior Translator"], mid=["Translator", "Localisation Specialist"], senior=["Senior Translator"],
                    lead=["Localisation Lead"], head=["Localisation Manager"]),
        freelance_title="Freelance Translator",
        industries=w("Translation agency:3; Software / SaaS:1; EU institution:1; Gaming:1; Manufacturing:1; Law firm:1"),
        education=w("master:6; bachelor:4"),
        fields=["Translation Studies", "Linguistics", "Modern Languages", "English Philology"],
        sizes="agency", work=w("remote:6; hybrid:3; office:1"), employment=w("employee:3; freelancer:7"),
        salary=0.85, globalized=0.2, intensity=0.9,
        tools=w("DeepL:9; ChatGPT:6; Claude:4; CAT tool with machine translation (Trados, memoQ):5; Google Translate:2; Gemini:1"),
        uses=["post-editing machine translation", "terminology research", "consistency checks", "adapting tone in marketing texts",
              "building glossaries", "quality checks"],
        attitudes=w("enthusiast:0.7; pragmatist:3; cautious:3; skeptic:4"),
        concerns=w("job:5; pay:4; accuracy:3; privacy:2; bland:2"),
        wins=["AI caught an inconsistency across a 200-page manual that I had missed"],
        fails=["clients now send raw machine translation and pay half for 'post-editing' that is really a full rewrite"]),
    dict(
        key="architect", label="Architect", weight=1.5, female=0.45, min_age=24,
        titles=dict(junior=["Junior Architect"], mid=["Architect"], senior=["Senior Architect", "Project Architect"],
                    lead=["Associate"], head=["Partner"]),
        freelance_title="Self-employed Architect",
        industries=w("Architecture firm:6; Construction:2; Real estate development:1; Public sector:1"),
        education=w("master:8; bachelor:2"),
        fields=["Architecture", "Urban Planning", "Interior Architecture"],
        sizes="agency", work=w("office:4; hybrid:6"), employment=w("employee:7; freelancer:3"),
        salary=1.05, globalized=0.1, intensity=0.55,
        tools=w("Midjourney:5; ChatGPT:7; Stable Diffusion:2; Adobe Firefly:2; AI rendering plug-ins:2; Claude:2"),
        uses=["concept visualisations for early client meetings", "project descriptions and competition texts",
              "summarising building regulations", "drafting specifications", "editing images for presentations"],
        attitudes=w("enthusiast:2; pragmatist:5; cautious:2; skeptic:2"),
        concerns=w("accuracy:3; copyright:2; bland:2; job:1"),
        wins=["clients understand a concept much faster from three AI mood images than from sketches"],
        fails=["a client fell in love with an AI render that was structurally impossible"]),
    dict(
        key="engineer", label="Engineer (mechanical / civil / electrical)", weight=3, female=0.2, min_age=22,
        titles=dict(junior=["Junior Engineer"], mid=["Mechanical Engineer", "Civil Engineer", "Electrical Engineer", "Process Engineer",
                                                    "Quality Engineer"],
                    senior=["Senior Engineer"], lead=["Lead Engineer"], head=["Head of Engineering"]),
        freelance_title="Freelance Engineering Consultant",
        industries=w("Automotive:3; Manufacturing:3; Construction:2; Energy:2; Aerospace:1; Engineering consultancy:2; Railways:1"),
        education=w("master:6; bachelor:4; vocational:1"),
        fields=["Mechanical Engineering", "Civil Engineering", "Electrical Engineering", "Chemical Engineering",
                "Mechatronics"],
        sizes="corp", work=w("office:3; hybrid:7"), employment=w("employee:9; freelancer:1"),
        salary=1.25, globalized=0.1, intensity=0.55,
        tools=w("ChatGPT:7; Microsoft Copilot:5; internal company AI assistant:3; Claude:3; GitHub Copilot:2; DeepL:3; Gemini:2"),
        uses=["writing technical reports", "Python and MATLAB scripts for calculations", "finding the right standard (then checking it)",
              "translating technical documentation", "FMEA brainstorming", "summarising supplier specs"],
        attitudes=w("enthusiast:1.5; pragmatist:6; cautious:2; skeptic:1.5"),
        concerns=w("accuracy:4; privacy:3; deskilling:2; security:1"),
        wins=["automated a tedious tolerance calculation with a Python script ChatGPT helped me write"],
        fails=["it quoted a DIN standard section that doesn't say what it claimed"]),
    dict(
        key="founder", label="Startup founder", weight=2.5, female=0.3, min_age=23, max_years=20,
        titles=dict(mid=["Founder & CEO", "Co-founder & CEO", "Co-founder & CTO", "Co-founder"]),
        industries=w("Startup (SaaS):3; Startup (climate tech):1; Startup (HealthTech):1; Startup (FinTech):1; E-commerce:1; Digital agency:1"),
        education=w("master:5; bachelor:4; none:1; phd:0.5"),
        fields=["Business Administration", "Computer Science", "Engineering", "Economics", "Design"],
        sizes="agency", work=w("remote:3; hybrid:6; office:1"), employment=w("founder:10"),
        salary=1.0, globalized=0.3, intensity=0.95,
        tools=w("ChatGPT:8; Claude:7; Perplexity:4; Cursor:3; Lovable:3; Gemini:2; Canva Magic Studio:3; Notion AI:2; "
                "automation tools with AI (n8n, Make):2"),
        uses=["investor updates and pitch decks", "market research", "building MVP prototypes",
              "drafting contracts and terms (then a lawyer checks)", "marketing copy", "automating customer support", "hiring"],
        attitudes=w("enthusiast:6; pragmatist:3; cautious:0.5; skeptic:0.2"),
        concerns=w("cost:2; dependence:2; accuracy:2; privacy:2; ai_act:1"),
        wins=["we run the company with five people where two years ago we would have needed twelve",
              "built the first MVP without hiring a developer"],
        fails=["an AI-built landing page promised a feature we didn't have yet"]),
    dict(
        key="small_business", label="Small business owner", weight=2, female=0.45, min_age=24,
        titles=dict(mid=["Owner of a café", "Owner of a bakery", "Owner of a hair salon", "Owner of a bicycle shop",
                         "Owner of an online ceramics shop", "Owner of a small accounting office",
                         "Owner of a boutique hotel", "Owner of a physiotherapy practice", "Owner of a florist",
                         "Owner of a craft brewery", "Owner of a driving school"]),
        industries=w("Small business:1"),
        education=w("vocational:5; bachelor:3; secondary:2; master:1"),
        fields=["Business Administration", "Hospitality", "Crafts", "Physiotherapy", "Design"],
        sizes="practice", work=w("office:10"), employment=w("self_employed:10"),
        salary=0.9, globalized=0.0, intensity=0.45,
        tools=w("ChatGPT:9; Canva Magic Studio:5; Gemini:2; DeepL:2; Meta AI:1; Microsoft Copilot:1"),
        uses=["social media posts", "product and menu descriptions", "replying to online reviews",
              "supplier and customer emails", "flyers and price lists", "understanding letters from the tax office",
              "writing job ads"],
        attitudes=w("enthusiast:3; pragmatist:6; cautious:1.5; skeptic:1"),
        concerns=w("accuracy:2; privacy:1; cost:2; bland:2"),
        wins=["answering Google reviews used to take my Sunday, now it's ten minutes",
              "finally understood a tax office letter without calling my accountant"],
        fails=["an AI-written Instagram post sounded nothing like us and a regular customer joked about it"]),
    dict(
        key="ecommerce", label="E-commerce manager", weight=1.5, female=0.5, min_age=22, max_years=20,
        titles=dict(junior=["E-commerce Specialist"], mid=["E-commerce Manager", "Marketplace Manager"],
                    senior=["Senior E-commerce Manager"], lead=["E-commerce Lead"], head=["Head of E-commerce"]),
        industries=w("E-commerce & retail:4; Fashion:2; Consumer goods:2; Home & furniture:1"),
        education=w("bachelor:6; master:3; vocational:1"),
        fields=["Business Administration", "Marketing", "Economics"],
        sizes="smb", work=w("remote:2; hybrid:6; office:2"), employment=w("employee:9; freelancer:1"),
        salary=1.05, globalized=0.1, intensity=0.85,
        tools=w("ChatGPT:8; Shopify Magic:3; Photoroom:3; Midjourney:2; Claude:2; DeepL:3; Gemini:2"),
        uses=["product descriptions in several languages", "editing product photos", "customer email templates", "SEO",
              "analysing customer reviews", "ad copy"],
        attitudes=w("enthusiast:4; pragmatist:5; cautious:1; skeptic:0.7"),
        concerns=w("bland:3; accuracy:2; copyright:2; job:1"),
        wins=["wrote 400 product descriptions in four languages in a week"],
        fails=["AI product descriptions invented a material the product isn't made of"]),
    dict(
        key="real_estate", label="Real estate agent", weight=1, female=0.5, min_age=22,
        titles=dict(junior=["Junior Real Estate Agent"], mid=["Real Estate Agent", "Property Manager"], senior=["Senior Real Estate Agent"],
                    head=["Broker"]),
        freelance_title="Independent Real Estate Agent",
        industries=w("Real estate:1"),
        education=w("vocational:4; bachelor:5; master:1"),
        fields=["Real Estate Management", "Business Administration", "Law"],
        sizes="smb", work=w("office:5; hybrid:5"), employment=w("employee:6; freelancer:4"),
        salary=1.0, globalized=0.0, intensity=0.55,
        tools=w("ChatGPT:8; AI virtual staging app:3; Canva Magic Studio:3; DeepL:2; Gemini:2"),
        uses=["listing descriptions", "virtual staging of empty flats", "client emails", "summarising lease agreements",
              "social media posts"],
        attitudes=w("enthusiast:3; pragmatist:6; cautious:1; skeptic:1"),
        concerns=w("accuracy:2; bland:2; privacy:1; misinfo:1"),
        wins=["virtual staging helped sell an empty flat that had been online for months"],
        fails=["a buyer complained that the staged photos were misleading"]),
    dict(
        key="video_creator", label="Video editor / content creator", weight=1.5, female=0.4, min_age=20, max_years=25,
        titles=dict(junior=["Junior Video Editor"], mid=["Video Editor", "Motion Designer", "Content Creator"],
                    senior=["Senior Video Editor"], lead=["Head of Video"]),
        freelance_title="Freelance Video Editor",
        industries=w("Media:3; Advertising agency:3; Online media:2; Education:1"),
        education=w("bachelor:5; vocational:3; none:2"),
        fields=["Film Studies", "Media Design", "Communication Studies"],
        sizes="agency", work=w("remote:4; hybrid:5; office:1"), employment=w("employee:4; freelancer:6"),
        salary=0.9, globalized=0.3, intensity=0.85,
        tools=w("CapCut:5; Descript:4; Runway:4; ElevenLabs:4; ChatGPT:7; Adobe Premiere Pro AI features:4; Midjourney:2; "
                "Opus Clip:2; AI video generators (Veo, Sora):1.5"),
        uses=["script writing", "automatic subtitles", "cleaning up audio", "cutting shorts from long videos", "voice-overs",
              "generating B-roll", "thumbnail ideas"],
        attitudes=w("enthusiast:3; pragmatist:4; cautious:2; skeptic:2"),
        concerns=w("copyright:4; job:3; bland:2; misinfo:2"),
        wins=["subtitles in five languages used to be a whole day, now it's a coffee break"],
        fails=["an AI voice-over mispronounced the client's brand name in the final export"]),
    dict(
        key="game_dev", label="Game developer / designer", weight=1, female=0.25, min_age=21,
        titles=dict(junior=["Junior Game Developer"], mid=["Game Developer", "Game Designer", "Technical Artist"],
                    senior=["Senior Gameplay Programmer"], lead=["Lead Game Designer"], head=["Studio Director"]),
        freelance_title="Indie Game Developer",
        industries=w("Gaming:1"),
        education=w("bachelor:6; master:2; none:2"),
        fields=["Computer Science", "Game Design", "Media Design"],
        sizes="agency", work=w("remote:3; hybrid:6; office:1"), employment=w("employee:7; freelancer:3"),
        salary=1.1, globalized=0.4, intensity=0.8,
        tools=w("GitHub Copilot:5; ChatGPT:6; Claude:4; Midjourney:3; Cursor:3; ElevenLabs:1"),
        uses=["gameplay code", "prototyping mechanics", "first drafts of item descriptions and dialogue",
              "concept art exploration", "debugging shaders"],
        attitudes=w("enthusiast:2; pragmatist:4; cautious:2; skeptic:3"),
        concerns=w("copyright:4; job:3; bland:2; deskilling:1"),
        wins=["prototyped a new mechanic in a day instead of a week"],
        fails=["players spotted AI-generated art in a trailer and the backlash was brutal"]),
    dict(
        key="civil_servant", label="Civil servant / policy officer", weight=3, female=0.55, min_age=23,
        titles=dict(junior=["Administrative Officer"], mid=["Policy Officer", "Case Officer", "Administrator"],
                    senior=["Senior Policy Adviser"], lead=["Deputy Head of Unit"], head=["Head of Unit"]),
        industries=w("National ministry:3; City administration:3; EU institution:1.5; Regional government:2; Public agency:2"),
        education=w("master:6; bachelor:4"),
        fields=["Law", "Political Science", "Public Administration", "Economics", "Sociology", "European Studies"],
        sizes="public", work=w("hybrid:7; office:3"), employment=w("employee:10"),
        salary=1.0, globalized=0.0, intensity=0.5,
        tools=w("Microsoft Copilot:6; ChatGPT:4; internal government AI assistant:3; DeepL:5; Mistral Le Chat:1; Claude:1"),
        uses=["drafting briefing notes", "summarising consultation responses", "plain-language rewrites of official letters",
              "translating documents", "meeting minutes", "comparing legislation across countries"],
        attitudes=w("enthusiast:1.5; pragmatist:4; cautious:5; skeptic:2"),
        concerns=w("privacy:4; accuracy:4; dependence:3; ai_act:2; bias:2"),
        wins=["summarised 1,200 consultation responses into themes in days instead of weeks"],
        fails=["a draft answer to a citizen cited a regulation that had been repealed"]),
    dict(
        key="trainer", label="Corporate trainer / L&D specialist", weight=1, female=0.65, min_age=24,
        titles=dict(mid=["L&D Specialist", "Corporate Trainer", "Instructional Designer"], senior=["Senior Learning Designer"],
                    lead=["L&D Lead"], head=["Head of Learning & Development"]),
        freelance_title="Freelance Trainer",
        industries=w("Manufacturing:1; Software / SaaS:1; FinTech & banking:1; Retail:1; Training provider:2"),
        education=w("master:5; bachelor:5"),
        fields=["Education", "Psychology", "Business Administration", "Communication Studies"],
        sizes="corp", work=w("remote:2; hybrid:6; office:2"), employment=w("employee:6; freelancer:4"),
        salary=1.0, globalized=0.0, intensity=0.8,
        tools=w("ChatGPT:8; Synthesia:3; Claude:3; Canva Magic Studio:3; Microsoft Copilot:3; DeepL:2; HeyGen:1; Articulate AI:1"),
        uses=["designing course outlines", "creating quizzes", "video scripts with AI avatars", "translating training content",
              "role-play scenarios for practice"],
        attitudes=w("enthusiast:4; pragmatist:4; cautious:1.5; skeptic:1"),
        concerns=w("bland:3; accuracy:2; human:2; job:1"),
        wins=["produced a compliance training in six languages without a film crew"],
        fails=["learners found the AI avatar videos creepy and stopped watching"]),
    dict(
        key="hospitality", label="Hotel / restaurant manager", weight=1, female=0.5, min_age=23,
        titles=dict(mid=["Front Office Manager", "Restaurant Manager", "Revenue Manager"], senior=["Hotel Operations Manager"],
                    head=["Hotel Manager", "General Manager"]),
        industries=w("Tourism & hospitality:1"),
        education=w("vocational:5; bachelor:4; master:1"),
        fields=["Hospitality Management", "Tourism", "Business Administration"],
        sizes="smb", work=w("office:10"), employment=w("employee:10"),
        salary=0.9, globalized=0.0, intensity=0.5,
        tools=w("ChatGPT:8; DeepL:4; Gemini:2; Canva Magic Studio:2; Microsoft Copilot:2"),
        uses=["replying to guest reviews", "guest emails in several languages", "menu and event descriptions", "staff schedules",
              "social media posts"],
        attitudes=w("enthusiast:2; pragmatist:6; cautious:1.5; skeptic:1"),
        concerns=w("bland:2; human:2; privacy:1; accuracy:1"),
        wins=["we reply to every review now, in the guest's own language"],
        fails=["an AI reply to an angry review sounded so corporate it made things worse"]),
    dict(
        key="tradesperson", label="Tradesperson", weight=1, female=0.08, min_age=20,
        titles=dict(mid=["Electrician", "Plumber", "Carpenter", "HVAC Technician", "Solar Panel Installer"],
                    senior=["Master Electrician", "Master Carpenter"]),
        freelance_title="Self-employed Electrician",
        industries=w("Construction & trades:1"),
        education=w("vocational:9; secondary:1"),
        fields=["Electrical Installation", "Plumbing", "Carpentry", "Heating & Ventilation"],
        sizes="practice", work=w("office:10"), employment=w("employee:5; self_employed:5"),
        salary=0.85, globalized=0.0, intensity=0.3,
        tools=w("ChatGPT:9; Gemini:2; Microsoft Copilot:1; Meta AI:1"),
        uses=["writing quotes and invoice texts", "customer emails", "looking up regulations (then verifying)",
              "troubleshooting ideas", "posts for the company's Facebook page", "translating for foreign colleagues"],
        attitudes=w("enthusiast:1.5; pragmatist:6; cautious:1; skeptic:2"),
        concerns=w("accuracy:3; cost:1; bland:1"),
        wins=["quotes that used to eat my evening now take five minutes"],
        fails=["ChatGPT gave me a wiring rule from the wrong country's standard"]),
    dict(
        key="agronomist", label="Agronomist / farm manager", weight=0.8, female=0.3, min_age=23,
        titles=dict(mid=["Agronomist", "Farm Manager", "Agricultural Consultant"], senior=["Senior Agronomist"]),
        freelance_title="Farmer",
        industries=w("Agriculture:1"),
        education=w("bachelor:5; master:3; vocational:2"),
        fields=["Agricultural Science", "Agronomy", "Environmental Science"],
        sizes="smb", work=w("office:10"), employment=w("employee:5; self_employed:5"),
        salary=0.85, globalized=0.0, intensity=0.4,
        tools=w("ChatGPT:7; precision-farming platform with AI:3; plant disease recognition app:2; Gemini:2"),
        uses=["identifying plant diseases from photos", "reading CAP subsidy rules", "planning fertiliser use", "writing reports",
              "weather risk planning"],
        attitudes=w("enthusiast:2; pragmatist:5; cautious:2; skeptic:2"),
        concerns=w("accuracy:3; cost:2; dependence:2; privacy:1"),
        wins=["a photo app identified a fungal infection early enough to save a field"],
        fails=["it summarised a subsidy rule wrongly and I nearly missed a deadline"]),
    dict(
        key="musician", label="Composer / sound designer", weight=0.6, female=0.35, min_age=20,
        titles=dict(mid=["Composer", "Sound Designer", "Music Producer"]),
        freelance_title="Freelance Sound Designer",
        industries=w("Media:2; Gaming:1; Advertising agency:1; Music:2"),
        education=w("bachelor:5; master:3; none:2"),
        fields=["Music", "Audio Engineering", "Media Design"],
        sizes="practice", work=w("remote:5; hybrid:4; office:1"), employment=w("employee:3; freelancer:7"),
        salary=0.8, globalized=0.2, intensity=0.6,
        tools=w("ChatGPT:5; iZotope AI tools:5; Moises:4; LANDR AI mastering:3; Suno:2; ElevenLabs:2"),
        uses=["stem separation", "audio repair", "mastering drafts", "grant applications and bios", "reference ideas"],
        attitudes=w("enthusiast:1; pragmatist:4; cautious:2; skeptic:4"),
        concerns=w("copyright:5; job:4; bland:3; pay:3"),
        wins=["separated stems from an old demo recording that I thought was lost"],
        fails=["a client asked for 'something like Suno but cheaper'"]),
    dict(
        key="lab_scientist", label="Pharma / biotech scientist", weight=1.2, female=0.55, min_age=23,
        titles=dict(junior=["Junior Scientist"], mid=["Research Scientist", "Scientist"], senior=["Senior Scientist"],
                    lead=["Principal Scientist"], head=["Head of R&D"]),
        industries=w("Pharmaceuticals:5; Biotech:4; Chemicals:2; Contract research organisation:1"),
        education=w("phd:5; master:4; vocational:1"),
        fields=["Biology", "Chemistry", "Biochemistry", "Pharmacy", "Biotechnology"],
        sizes="corp", work=w("office:6; hybrid:4"), employment=w("employee:10"),
        salary=1.3, globalized=0.2, intensity=0.6,
        tools=w("ChatGPT:6; Claude:4; internal company AI assistant:3; Microsoft Copilot:3; Elicit:2; AlphaFold:2; GitHub Copilot:2"),
        uses=["literature reviews", "writing SOPs and protocols", "data analysis scripts", "protein structure prediction",
              "drafting regulatory documents"],
        attitudes=w("enthusiast:2; pragmatist:5; cautious:3; skeptic:1"),
        concerns=w("accuracy:4; privacy:3; ai_act:1; dependence:1"),
        wins=["drafted a 30-page SOP from our old notes in an afternoon"],
        fails=["a literature summary mixed up results from two different trials"]),
    dict(
        key="banking", label="Bank / insurance specialist", weight=2, female=0.5, min_age=21,
        titles=dict(junior=["Client Service Associate"], mid=["Client Advisor", "Underwriter", "Claims Handler", "Credit Analyst"],
                    senior=["Senior Relationship Manager", "Senior Underwriter"], lead=["Team Lead Claims"],
                    head=["Head of Risk"]),
        industries=w("Banking:5; Insurance:4"),
        education=w("bachelor:5; master:3; vocational:3"),
        fields=["Finance", "Economics", "Business Administration", "Law"],
        sizes="corp", work=w("hybrid:7; office:3"), employment=w("employee:10"),
        salary=1.15, globalized=0.0, intensity=0.55,
        tools=w("internal company AI assistant:6; Microsoft Copilot:5; ChatGPT:4; DeepL:2"),
        uses=["summarising client documents", "drafting client letters", "risk memos", "checking policy wording", "Excel analysis",
              "preparing client meetings"],
        attitudes=w("enthusiast:1.5; pragmatist:5; cautious:3; skeptic:1.5"),
        concerns=w("privacy:4; accuracy:4; job:2; policy:2"),
        wins=["the internal assistant summarises a 50-page claim file in a minute"],
        fails=["the bank's chatbot is so restricted that I end up doing it by hand anyway"]),
    # Weight 0: only used by the "marketing" audience (see MARKETING_AUDIENCE), so the general sample is unchanged.
    dict(
        key="pr_comms", label="PR / communications specialist", weight=0, female=0.65, min_age=21,
        titles=dict(junior=["PR Assistant", "Junior Communications Specialist"],
                    mid=["PR Specialist", "Communications Specialist", "Communications Manager"],
                    senior=["Senior Communications Manager", "Senior PR Manager"], lead=["Communications Lead"],
                    head=["Head of Communications", "Communications Director"]),
        freelance_title="Freelance PR Consultant",
        industries=w("PR agency:3; Non-profit:1.5; Public agency:1; Software / SaaS:1; Consumer goods:1; "
                     "Energy:0.5; University:0.5; Tourism & hospitality:0.5"),
        education=w("bachelor:5; master:5"),
        fields=["Communication Studies", "Journalism", "Public Relations", "Political Science", "Media Studies"],
        sizes="mixed", work=w("remote:2; hybrid:6; office:2"), employment=w("employee:8; freelancer:2"),
        salary=1.0, globalized=0.15, intensity=0.75,
        tools=w("ChatGPT:9; Claude:4; Gemini:3; Microsoft Copilot:3; Perplexity:3; DeepL:3; Canva Magic Studio:3; "
                "AI transcription (Whisper-based):2; Grammarly:1.5"),
        uses=["drafting press releases", "media monitoring summaries", "drafts of statements and speeches",
              "social media posts", "Q&A documents for spokespeople", "translating statements", "newsletter texts"],
        attitudes=w("enthusiast:2; pragmatist:5; cautious:3; skeptic:1.5"),
        concerns=w("accuracy:4; misinfo:3; bland:3; privacy:2; copyright:1.5"),
        wins=["turned a 20-page report into a press release draft in ten minutes",
              "summarised a week of media coverage before the Monday meeting"],
        fails=["an AI draft of a statement put words in our CEO's mouth that he never said",
               "a press release draft used a statistic nobody could find a source for"]),
    dict(
        key="performance_marketer", label="SEO / paid media specialist", weight=0, female=0.45, min_age=21,
        max_years=18,
        titles=dict(junior=["Junior SEO Specialist", "PPC Assistant"],
                    mid=["SEO Specialist", "PPC Specialist", "Paid Social Specialist", "Performance Marketing Manager"],
                    senior=["Senior SEO Specialist", "Senior Paid Media Manager"],
                    lead=["Performance Marketing Lead", "SEO Lead"], head=["Head of Performance Marketing"]),
        freelance_title="Freelance SEO & Ads Consultant",
        industries=w("Digital agency:4; E-commerce & retail:2; Software / SaaS:1.5; Tourism & hospitality:1; "
                     "FinTech & banking:0.5"),
        education=w("bachelor:6; master:3; none:1"),
        fields=["Marketing", "Business Administration", "Economics", "Computer Science", "Media Studies"],
        sizes="agency", work=w("remote:4; hybrid:5; office:1"), employment=w("employee:7; freelancer:3"),
        salary=1.05, globalized=0.3, intensity=0.95,
        tools=w("ChatGPT:9; Google Ads AI features (Performance Max):6; Meta Advantage+:5; Semrush AI:4; "
                "Surfer SEO:3; Claude:4; Gemini:4; GA4 predictive insights:2; Perplexity:2"),
        uses=["ad copy variations", "keyword research and clustering", "writing meta descriptions",
              "Performance Max campaigns", "analysing campaign data", "monthly client reports",
              "landing page copy tests", "search intent analysis"],
        attitudes=w("enthusiast:4; pragmatist:5; cautious:1; skeptic:0.7"),
        concerns=w("accuracy:3; bland:2; cost:1.5; dependence:2; job:1; privacy:1"),
        wins=["cut the time for monthly client reports from a day to two hours",
              "AI keyword clustering found a niche that became our best-converting campaign"],
        fails=["Performance Max spent half the budget on placements we would never have chosen",
               "an AI tool suggested keywords with zero search volume in our market"]),
]

PROFESSIONS_BY_KEY = {p["key"]: p for p in PROFESSIONS}

# Tools that the employer typically pays for in bigger companies.
ENTERPRISE_TOOLS = {
    "Microsoft Copilot", "GitHub Copilot", "ChatGPT", "Claude", "Gemini", "internal company AI assistant",
    "internal government AI assistant", "Harvey", "Legora", "Zendesk AI", "Intercom Fin", "Salesforce Agentforce",
    "Microsoft Security Copilot", "Cursor", "Claude Code", "AI medical scribe", "Notion AI", "Atlassian Intelligence",
    "Figma AI", "Adobe Firefly", "Adobe Photoshop Generative Fill", "DeepL", "CoCounsel", "Gong",
}

# --------------------------------------------------------------------------- #
# "marketing" audience: people who did marketing or promotion in the last 12 months
# --------------------------------------------------------------------------- #
# Profession weights. A small share of other professions stands for people who received the survey link
# but do not work in marketing (they are screened out by an eligibility question).
MARKETING_AUDIENCE = w("marketing:10; performance_marketer:4; social_media:5; content_writer:4; pr_comms:4; "
                       "ecommerce:3; graphic_designer:2; video_creator:1.5; small_business:5; founder:2; sales:1.5")
NON_MARKETER_SHARE = 0.04

# The marketing tasks of the questionnaire, in the order of its task grid.
MARKETING_TASKS = ["audience_research", "strategy", "segmentation", "copywriting", "visuals", "ads", "community",
                   "reporting"]
MARKETING_TASK_LABELS = {
    "audience_research": "audience and market analysis", "strategy": "strategy, goals and KPI planning",
    "segmentation": "segmentation, personas and personalisation", "copywriting": "writing promotional content",
    "visuals": "creating or editing images and video", "ads": "running or optimising ad campaigns",
    "community": "audience communication, customer service and chatbots", "reporting": "results analysis and reporting",
}
# How likely someone in this profession does the task at all.
MARKETING_TASK_PROFILES = {
    "marketing": dict(audience_research=.85, strategy=.8, segmentation=.7, copywriting=.85, visuals=.6, ads=.7,
                      community=.4, reporting=.9),
    "performance_marketer": dict(audience_research=.8, strategy=.6, segmentation=.85, copywriting=.7, visuals=.35,
                                 ads=1, community=.15, reporting=1),
    "social_media": dict(audience_research=.7, strategy=.5, segmentation=.4, copywriting=.95, visuals=.9, ads=.55,
                         community=.95, reporting=.8),
    "content_writer": dict(audience_research=.6, strategy=.35, segmentation=.35, copywriting=1, visuals=.3, ads=.25,
                           community=.25, reporting=.4),
    "pr_comms": dict(audience_research=.7, strategy=.75, segmentation=.4, copywriting=.95, visuals=.45, ads=.25,
                     community=.8, reporting=.7),
    "ecommerce": dict(audience_research=.75, strategy=.6, segmentation=.7, copywriting=.8, visuals=.7, ads=.8,
                      community=.6, reporting=.9),
    "graphic_designer": dict(audience_research=.25, strategy=.2, segmentation=.1, copywriting=.35, visuals=1, ads=.3,
                             community=.1, reporting=.15),
    "video_creator": dict(audience_research=.3, strategy=.2, segmentation=.1, copywriting=.6, visuals=1, ads=.3,
                          community=.35, reporting=.3),
    "small_business": dict(audience_research=.4, strategy=.35, segmentation=.2, copywriting=.95, visuals=.85, ads=.5,
                           community=.9, reporting=.35),
    "founder": dict(audience_research=.85, strategy=.9, segmentation=.6, copywriting=.8, visuals=.5, ads=.55,
                    community=.6, reporting=.7),
    "sales": dict(audience_research=.7, strategy=.35, segmentation=.6, copywriting=.7, visuals=.2, ads=.2,
                  community=.7, reporting=.6),
}
# How common AI help is for each task among marketers who use AI (0..1).
MARKETING_TASK_AI_AFFINITY = dict(audience_research=.55, strategy=.4, segmentation=.45, copywriting=.85,
                                  visuals=.6, ads=.5, community=.45, reporting=.45)
# Words in a persona's AI use cases that point to a task.
MARKETING_TASK_WORDS = {
    "audience_research": ["research", "trend", "market", "reviews", "prospect", "intent", "monitoring"],
    "strategy": ["brainstorm", "strategy", "plan", "calendar", "pitch"],
    "segmentation": ["segment", "persona", "personalis", "audiences", "different audiences"],
    "copywriting": ["post", "copy", "caption", "blog", "newsletter", "article", "headline", "description", "hooks",
                    "outreach", "press release", "statement", "writing", "texts", "draft", "seo", "meta"],
    "visuals": ["visual", "image", "photo", "video", "clip", "thumbnail", "b-roll", "mockup", "moodboard",
                "subtitle", "flyer", "voice-over", "retouch", "concept art"],
    "ads": ["ad copy", "ads", "campaign", "keyword", "performance max", "localising"],
    "community": ["replying", "comments", "review", "customer", "support", "chatbot", "q&a"],
    "reporting": ["analys", "report", "performance", "dashboard", "summar"],
}
# Levels of AI use per task (task-grid columns); "no" = does not do this task.
AI_TASK_LEVELS = ["never", "few", "some", "most", "almost always"]

# What kind of AI tool each tool is (for "which types of AI tools do you use").
TOOL_KINDS = {
    "text": {"ChatGPT", "Claude", "Gemini", "Microsoft Copilot", "Perplexity", "Mistral Le Chat", "Jasper",
             "Grammarly", "Notion AI", "Meta AI", "DeepSeek", "Surfer SEO", "internal company AI assistant",
             "HubSpot Breeze AI", "Shopify Magic"},
    "visual": {"Canva Magic Studio", "Midjourney", "Adobe Firefly", "Adobe Photoshop Generative Fill", "CapCut",
               "Opus Clip", "Runway", "Descript", "Photoroom", "Ideogram", "Krea", "HeyGen", "Synthesia",
               "AI video generators (Veo, Sora)", "Adobe Premiere Pro AI features", "Figma AI"},
    "ads": {"HubSpot Breeze AI", "Google Ads AI features (Performance Max)", "Meta Advantage+", "Salesforce Agentforce",
            "automation tools with AI (n8n, Make)", "Shopify Magic"},
    "analytics": {"GA4 predictive insights", "Semrush AI", "Julius AI", "Gong"},
    "chatbot": {"Intercom Fin", "Zendesk AI", "website chatbot (Tidio AI)"},
    "other": {"DeepL", "DeepL Write", "ElevenLabs", "AI transcription (Whisper-based)", "Otter.ai", "Fireflies.ai"},
}
# Extra tools a marketer picks up for tasks that their profession's tool list does not cover.
MARKETING_EXTRA_TOOLS = {
    "ads": ["Meta Advantage+", "Google Ads AI features (Performance Max)"],
    "analytics": ["GA4 predictive insights", "Semrush AI"],
    "chatbot": ["website chatbot (Tidio AI)", "Intercom Fin"],
}

# Why some marketers do not use AI at all (probabilities depend on attitude, see the generator).
AI_NON_USE_REASONS = [
    "does not trust AI output for client work",
    "prefers to write and design everything personally",
    "the employer does not allow AI tools",
    "has not found the time to learn it",
    "does not see the need in a business this small",
    "worried about copyright and data protection",
]
